# Generated by Django 3.2.8 on 2021-10-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AbsoluteThrottlePosition', models.DecimalField(decimal_places=10, max_digits=10)),
                ('EngineKW', models.DecimalField(decimal_places=10, max_digits=10)),
                ('EngineRPM', models.DecimalField(decimal_places=10, max_digits=10)),
                ('FfrHour', models.DecimalField(decimal_places=10, max_digits=10)),
                ('FfrM', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Horsepower', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Torque', models.DecimalField(decimal_places=10, max_digits=10)),
                ('Speed', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
