# Generated by Django 3.2.8 on 2021-10-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedmodel',
            name='AbsoluteThrottlePosition',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
