# Generated by Django 3.2.8 on 2021-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedApp', '0002_alter_speedmodel_absolutethrottleposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedmodel',
            name='EngineKW',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='speedmodel',
            name='EngineRPM',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='speedmodel',
            name='FfrHour',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='speedmodel',
            name='FfrM',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='speedmodel',
            name='Horsepower',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='speedmodel',
            name='Speed',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='speedmodel',
            name='Torque',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
