# Generated by Django 3.2.8 on 2021-10-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedApp', '0003_auto_20211011_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedmodel',
            name='AbsoluteThrottlePosition',
        ),
        migrations.RemoveField(
            model_name='speedmodel',
            name='FfrHour',
        ),
        migrations.RemoveField(
            model_name='speedmodel',
            name='FfrM',
        ),
    ]
