# Generated by Django 3.2.8 on 2021-10-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedApp', '0004_auto_20211013_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedmodel',
            name='Speed',
            field=models.TextField(),
        ),
    ]
